{{- define "sa.container_envs_db" }}
{{- if .Values.global.sa.db }}
  {{- if .Values.global.sa.db.secret }}
    {{- if .Values.global.sa.db.secret.create }}
      {{- $secret_name := ( include "sa-postgres.secretName" . ) }}
- name: SA_POSTGRESQL_HOST
  valueFrom:
    secretKeyRef:
      name: {{ $secret_name }}
      key: dbhost
- name: SA_POSTGRESQL_PORT
  valueFrom:
    secretKeyRef:
      name: {{ $secret_name }}
      key: dbport
- name: SA_POSTGRESQL_USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ $secret_name }}
      key: dbuser
- name: SA_POSTGRESQL_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ $secret_name }}
      key: dbpwd
    {{- else }}
      {{- $secret_name := .Values.global.sa.db.secret }}
- name: SA_POSTGRESQL_HOST
  value: {{ $secret_name.dbhost | quote }}
- name: SA_POSTGRESQL_PORT
  value: {{ $secret_name.dbport | quote }}
- name: SA_POSTGRESQL_USERNAME
  value: {{ $secret_name.dbuser | quote }}
- name: SA_POSTGRESQL_PASSWORD
  value: {{ $secret_name.dbpwd | quote }}
    {{- end }}
  {{- end }}
{{- else if .Values.global.db.secret.create }}
  {{- $secret_name := ( include "postgres.secretName" . ) }}
- name: SA_POSTGRESQL_HOST
  valueFrom:
    secretKeyRef:
      name: {{ $secret_name }}
      key: dbhost
- name: SA_POSTGRESQL_PORT
  valueFrom:
    secretKeyRef:
      name: {{ $secret_name }}
      key: dbport
- name: SA_POSTGRESQL_USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ $secret_name }}
      key: dbuser
- name: SA_POSTGRESQL_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ $secret_name }}
      key: dbpwd
{{- else }}
  {{- $secret_name := .Values.global.db.secret }}
- name: SA_POSTGRESQL_HOST
  value: {{ $secret_name.dbhost | quote }}
- name: SA_POSTGRESQL_PORT
  value: {{ $secret_name.dbport | quote }}
- name: SA_POSTGRESQL_USERNAME
  value: {{ $secret_name.dbuser | quote }}
- name: SA_POSTGRESQL_PASSWORD
  value: {{ $secret_name.dbpwd | quote }}
{{- end }}

{{- end }}