{{- $dbSecretData := .Values.global.db.secret.data }}
{{- $redisSecretData := .Values.global.redis.secret.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  labels:
{{- include "sa-singlespace.labels" . | nindent 4 }}
data:
  config.yml: |
    env: {{ .Values.global.env | default "prod" }}
    domain: {{ .Values.global.sa.subDomain }}.{{ .Values.global.domain }}
    {{- with .Values.global.sa.singlespace.config.secret }}
    secret: {{ . }}
    {{- end }}
    listen:
      type: port
      bind_ip: 0.0.0.0
      port: {{ .Values.global.sa.singlespace.port }}
    psql:
      host: {{ $dbSecretData.dbhost }}
      port: {{ $dbSecretData.dbport }}
      user: {{ $dbSecretData.dbuser }}
      password: {{ $dbSecretData.dbpwd }}
      database: accounts
    redis:
      host: {{ $redisSecretData.host }}
      port: {{ $redisSecretData.port | default "6379" }}
      password: {{ $redisSecretData.password | quote }}
      database: 11
    {{- if .Values.global.sa.tls_skip_verify }}
    tls:
      insecure_skip_verify: true
    {{- end }}
    {{- with .Values.global.sa.singlespace.config }}
      {{- with .keycloak }}
    keycloak:
      url: {{ .url }}
      realm: {{ .realm }}
      client: {{ .client }}
      sync: {{ .sync }}
      separator: {{ .separator }}
      {{- end }}
      {{- with .webhooks }}
        {{- with .on_invite }}
    webhooks:
      on_invite: {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}