{{- if .Values.global.sa.singlespace.serviceAccount }}
{{- if .Values.global.sa.singlespace.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.appName }}-role
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.appName }}-role-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.appName }}-serviceaccount
roleRef:
  kind: Role
  name: {{ .Values.appName }}-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-serviceaccount
  {{- with .Values.global.sa.singlespace.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end }}
{{- end }}
