apiVersion: v2
name: singlespace
description: A Helm chart for SingleSpace
icon: https://account.corezoid.com/static/logo.svg
type: application
version: 0.1.18
appVersion: 3.2.2
dependencies:
  - name: account-auth
    version: 0.1.1
  - name: account-frontend
    version: 0.1.0
  - name: account-ingress
    version: 0.1.2
  - name: account-workspace
    version: 0.1.1
