apiVersion: v2
name: singlespace
description: A Helm chart for Account
icon: https://account.corezoid.com/static/logo.svg
type: application
version: 0.2.27
appVersion: 3.20.0
dependencies:
  - name: account-auth
    version: 0.1.34
  - name: account-frontend
    version: 0.1.25
  - name: account-ingress
    version: 0.1.2
  - name: account-workspace
    version: 0.1.34
  - name: account-valkey
    version: 0.1.9
