{{- $global_data := .Values.global }}
{{- $account_data := $global_data.account }}
{{- if eq .Values.global.account.frontend.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account.frontend.configmap.name.nginx" . }}
  labels:
    {{- include "account.frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes 1;
    error_log /dev/stdout;
    pid        /var/run/nginx.pid;

    load_module /etc/nginx/modules/ngx_http_image_filter_module.so;

    events {
      worker_connections  32000;
      multi_accept on;
    }

    http {
      client_max_body_size 25m;
      server_names_hash_bucket_size 128;
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      log_format up_log '$server_addr\t$server_port\t$http_x_forwarded_for\t$time_iso8601\tforward-to $upstream_addr\t$request\t$status\t$body_bytes_sent\t$request_time\t$upstream_response_time\t$http_referer\t$http_user_agent\t$host';
      access_log /dev/stdout up_log;

      sendfile        on;
      tcp_nopush     on;

      server_tokens   off;
      # disable buffering
      proxy_buffering off;
      proxy_max_temp_file_size 0;
      keepalive_timeout  65;
      gzip on;
      gzip_types text/css application/x-javascript text/xml application/xml application/xml+rss text/plain application/javascript text/javascript application/json image/png image/svg+xml;
      gzip_proxied any;

      include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account.frontend.configmap.name.site" . }}
  labels:
    {{- include "account.frontend.labels" . | nindent 4 }}
data:
  {{ .Values.appName }}.conf: |
    server {
      listen {{ include "account.frontend.portNumber" . }};
      server_name {{ .Values.global.account.subDomain }}.{{ .Values.global.domain }};

      access_log /dev/stdout up_log;
      error_log  /dev/stdout;

      root /ebsmnt/www/mw-auth;
      set $avatars_local    /{{ .Values.global.account.persistantVolumeClaimShareDir }};

      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
      add_header X-Content-Type-Options nosniff;
      add_header X-Frame-Options SAMEORIGIN;
      add_header X-XSS-Protection "1; mode=block";
      add_header 'Referrer-Policy' 'origin-when-cross-origin';
      add_header Permissions-Policy "geolocation=(), camera=()";
      add_header Content-Security-Policy "default-src 'self' blob: 'unsafe-inline' 'unsafe-eval' data: https://unpkg.com wss://*.{{ .Values.global.env }}.{{ .Values.global.domain }} https://{{ .Values.global.account.subDomain}}.{{ .Values.global.domain }}  https://*.control.events https://img.icons8.com/ https://www.google-analytics.com https://fonts.gstatic.com https://www.googletagmanager.com https://*.{{ .Values.global.env }}.{{ .Values.global.domain }} https://github.com https://www.facebook.com https://appleid.apple.com https://*.ngrok-free.app https://*.google.com https://stats.g.doubleclick.net https://fonts.googleapis.com https://*.google.com.ua https://*.shopify.com https://shopify.com https://*.googleusercontent.com https://*.simulator.company;";

      location @redirect {
          return 302 /avatars/54x54/0.jpg;
      }

      location /avatars {

        add_header      Content-Type image/jpeg;
        error_page 404 415 = @redirect;
        alias $avatars_local;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        add_header 'Referrer-Policy' 'origin-when-cross-origin';
        add_header Permissions-Policy "geolocation=(), camera=()";
        add_header Content-Security-Policy "default-src 'self' blob: 'unsafe-inline' 'unsafe-eval' data: https://unpkg.com wss://*.{{ .Values.global.env }}.{{ .Values.global.domain }} https://{{ .Values.global.account.subDomain}}.{{ .Values.global.domain }}  https://*.control.events https://img.icons8.com/ https://www.google-analytics.com https://fonts.gstatic.com https://www.googletagmanager.com https://*.{{ .Values.global.env }}.{{ .Values.global.domain }} https://github.com https://www.facebook.com https://appleid.apple.com https://*.ngrok-free.app https://*.google.com https://stats.g.doubleclick.net https://fonts.googleapis.com https://*.google.com.ua https://*.shopify.com https://shopify.com https://*.googleusercontent.com https://*.simulator.company;";

      }

      location ~ ^/avatars/(.+)x(.+)/(.+) {
        set                         $width  $1;
        set                         $height $2;

        proxy_http_version 1.1;
        add_header      Content-Type image/jpeg;
        error_page 404 415 = @redirect;
        alias $avatars_local/$3;

        expires 1d;
        image_filter                crop  $width  $height;
        image_filter_buffer 20M;
        image_filter_jpeg_quality 75; # Desired JPG quality

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        add_header 'Referrer-Policy' 'origin-when-cross-origin';
        add_header Permissions-Policy "geolocation=(), camera=()";
        {{- if .Values.global.simulator }}
        add_header 'Access-Control-Allow-Origin' 'https://{{ .Values.global.simulator.subDomain}}.{{ .Values.global.simulator.mainDomian }}';
        {{- end }}
        add_header Content-Security-Policy "default-src 'self' blob: 'unsafe-inline' 'unsafe-eval' data: https://unpkg.com wss://*.{{ .Values.global.env }}.{{ .Values.global.domain }} https://{{ .Values.global.account.subDomain}}.{{ .Values.global.domain }}  https://*.control.events https://img.icons8.com/ https://www.google-analytics.com https://fonts.gstatic.com https://www.googletagmanager.com https://*.{{ .Values.global.env }}.{{ .Values.global.domain }} https://github.com https://www.facebook.com https://appleid.apple.com https://*.ngrok-free.app https://*.google.com https://stats.g.doubleclick.net https://fonts.googleapis.com https://*.google.com.ua https://*.shopify.com https://shopify.com https://*.googleusercontent.com https://*.simulator.company;";

      }

      location / {
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        add_header 'Referrer-Policy' 'origin-when-cross-origin';
        add_header Permissions-Policy "geolocation=(), camera=()";
        add_header Content-Security-Policy "default-src 'self' blob: 'unsafe-inline' 'unsafe-eval' data: https://unpkg.com wss://*.{{ .Values.global.env }}.{{ .Values.global.domain }} https://{{ .Values.global.account.subDomain}}.{{ .Values.global.domain }} https://www.keycloak.org/ https://*.control.events https://img.icons8.com/ https://www.google-analytics.com https://fonts.gstatic.com https://www.googletagmanager.com https://*.{{ .Values.global.domain }} https://github.com https://www.facebook.com https://appleid.apple.com https://*.ngrok-free.app https://*.google.com https://stats.g.doubleclick.net https://fonts.googleapis.com https://*.google.com.ua https://*.shopify.com https://shopify.com https://*.googleusercontent.com https://*.simulator.company https://www.gstatic.com https://aadcdn.msauth.net;";
        try_files $uri /index.html;
      }

      location ~ ^/(api|auth|oauth2|download) {
        proxy_pass http://{{ include "account.auth.service.name" . }}:{{ .Values.global.account.auth.port | default 80}};
        add_header Cache-Control "no-cache, must-revalidate";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        add_header 'Referrer-Policy' 'origin-when-cross-origin';
        add_header Permissions-Policy "geolocation=(), camera=()";
        add_header Content-Security-Policy "default-src 'self' blob: 'unsafe-inline' 'unsafe-eval' data: https://unpkg.com wss://*.{{ .Values.global.env }}.{{ .Values.global.domain }} https://{{ .Values.global.account.subDomain}}.{{ .Values.global.domain }} https://*.control.events https://img.icons8.com/ https://www.google-analytics.com https://fonts.gstatic.com https://www.googletagmanager.com https://*.{{ .Values.global.domain }} https://github.com https://www.facebook.com https://appleid.apple.com https://*.ngrok-free.app https://*.google.com https://stats.g.doubleclick.net https://fonts.googleapis.com https://*.google.com.ua https://*.shopify.com https://shopify.com https://*.googleusercontent.com https://*.simulator.company;";
     }

      location ~ ^/(client|public|face|webhook) {
        proxy_pass http://{{ include "account.workspace.service.name" . }}:{{ .Values.global.account.workspace.port | default 80}};
        add_header Cache-Control "no-cache, must-revalidate";
      }

    }
  {{- end }}