{{- $auth_config := .Values.global.account.auth }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account.auth.configmap.name" . }}
  labels:
    {{- include "account.auth.labels" . | nindent 4 }}
data:
  {{ .Values.configName }}: |
    env: {{ .Values.global.env | default "prod" }}
    type: {{ .Values.global.account.type | default "in_house" }}
    url: {{ .Values.global.account.protocol | default "https://" }}{{ .Values.global.account.subDomain }}.{{ .Values.global.domain }}
    webhook:
      url: {{ .Values.global.account.webhook.url }}
    secret: {{ .Values.global.account.secret }}
    listen:
      type: port
      bind_ip: 0.0.0.0
      port: {{ .Values.global.account.auth.port }}
    psql:
      host: ${POSTGRES_DBHOST}
      port: ${POSTGRES_DBPORT}
      user: ${POSTGRES_DBUSER}
      password: ${POSTGRES_DBPWD}
      database: ${DB_NAME}
    license_psql:
      host: ${POSTGRES_DBHOST}
      port: ${POSTGRES_DBPORT}
      user: ${POSTGRES_DBUSER}
      password: ${POSTGRES_DBPWD}
      database: {{ $auth_config.license_db | default "settings" }}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DB}
    {{- if .Values.global.account.tls_skip_verify }}
    tls:
      insecure_skip_verify: true
    {{- end }}
{{ $auth_config.config | toYaml | trim | indent 4 }}