{{- $global_data := .Values.global -}}
{{- $account_data := .Values.global.account -}}
{{- $auth_data := $account_data.auth -}}
{{- $app_name := (include "module.auth.name" . ) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account.auth.deployment.name" . }}
  labels:
    {{- include "account.auth.labels" . | nindent 4 }}
spec:
{{- if $auth_data.autoscaling }}
{{- if $auth_data.autoscaling.enabled }}
  replicas: {{ $auth_data.autoscaling.minReplicas }}
{{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "account.auth.labels" . | nindent 6 }}
{{- with $global_data.deploymentStrategy }}
  strategy:
{{ toYaml . | trim | indent 4 }}
{{- end }}
    {{- if eq $global_data.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "account.auth.labels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.global.imagePullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{- include "account.auth.serviceaccount.name" . | nindent 8 }}
      securityContext:
        {{- toYaml $account_data.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-wait-main-postgresql
          image: "{{ $global_data.imageInit.repository }}:{{ $global_data.imageInit.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - until nc -zvw1 ${POSTGRES_DBHOST} ${POSTGRES_DBPORT};
              do echo waiting for Database; sleep 2; done;
          env:
            {{- include "account.container_envs_db" . | trim | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      containers:
        - name: {{ include "module.auth.name" . }}
          securityContext:
            {{- toYaml $account_data.securityContext | nindent 14 }}
          image: {{ include "account.auth.imageUrl" . | quote }}
          imagePullPolicy: {{ $account_data.pullPolicy | default "IfNotPresent" }}
          env:
            - name: SS_CONFIG
              value: "{{ .Values.configPath }}/{{ .Values.configName }}"
            {{- if $auth_data.auth_providers_keys }}
            {{- if $auth_data.auth_providers_keys.apple }}
            - name: AUTH_APPLE_SECRET_PATH
              value: "{{ .Values.configPath }}/apple"
            {{- end }}
            {{- end }}
          {{- include "account.container_envs_redis" .  | trim | nindent 12 }}
          {{- include "account.container_envs_db" .  | trim | nindent 12 }}
          ports:
            - name: {{ include "account.auth.portHttpName" . }}
              containerPort: {{ include "account.auth.portNumber" . }}
              protocol: {{ include "account.auth.portProtocol" . }}
          {{- with $auth_data.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ $app_name }}-config-volume
              mountPath: {{ .Values.configPath }}/{{ .Values.configName }}
              subPath: {{ .Values.configName }}
            {{- if $account_data.config.auth_providers.saml }}
            {{- if $account_data.config.auth_providers.saml.google_saml }}
            {{- if eq $account_data.config.auth_providers.saml.google_saml.enabled true }}
            - name: metadata-google
              mountPath: /opt/conf/google_metadata.xml
              subPath: google_metadata.xml
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if $account_data.persistantVolumeClaimCreate }}
            - name: {{ $app_name }}-pvc
              mountPath: /{{ $account_data.persistantVolumeClaimShareDir }}
            {{- end }}
            {{- if $auth_data.auth_providers_keys }}
            {{- if $auth_data.auth_providers_keys.apple }}
            - name: auth-apple-secret
              mountPath: {{ .Values.configPath }}/apple
              subPath: apple
            {{- end }}
            {{- end }}
      volumes:
        - name: {{ $app_name }}-config-volume
          configMap:
            name: {{ include "account.auth.configmap.name" . }}
        {{- if $account_data.config.auth_providers.saml }}
        {{- if $account_data.config.auth_providers.saml.google_saml }}
        {{- if eq $account_data.config.auth_providers.saml.google_saml.enabled true }}
        - name: metadata-google
          secret:
            secretName: {{ $account_data.config.auth_providers.saml.google_saml.secret_name | default "metadata-google-secret" }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if $account_data.persistantVolumeClaimCreate }}
        - name: {{ $app_name }}-pvc
          persistentVolumeClaim:
            claimName: {{ $account_data.persistantVolumeClaimName }}
            readOnly: false
        {{- end }}
        {{- if $auth_data.auth_providers_keys }}
        {{- if $auth_data.auth_providers_keys.apple }}
        - name: auth-apple-secret
          secret:
            secretName: {{ include "account.auth_provider_secret_name" . }}
            items:
            - key: apple
              path: apple
        {{- end }}
        {{- end }}
      {{- with $account_data.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $account_data.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $account_data.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
