{{- $auth_data := .Values.global.account.auth }}
{{- $app_name := (include "module.auth.name" . ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account.auth.deployment.name" . }}
  labels:
    {{- include "account.auth.labels" . | nindent 4 }}
spec:
{{- if $auth_data.autoscaling }}
{{- if $auth_data.autoscaling.enabled }}
  replicas: {{ $auth_data.autoscaling.minReplicas }}
{{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "account.auth.labels" . | nindent 6 }}
{{- with .Values.global.deploymentStrategy }}
  strategy:
{{ toYaml . | trim | indent 4 }}
{{- end }}
{{- if eq .Values.global.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
{{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "account.auth.labels" . | nindent 8 }}
    spec:
      {{- if not (eq .Values.global.repotype "public") }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets.name }}-{{ .Values.global.env | default "prod" }}
      {{- end }}
      serviceAccountName: {{- include "account.auth.serviceaccount.name" . | nindent 8 }}
      securityContext:
        {{- toYaml .Values.global.account.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-wait-main-postgresql
          image: "{{ .Values.global.imageInit.repository }}:{{ .Values.global.imageInit.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - until nc -zvw1 ${POSTGRES_DBHOST} ${POSTGRES_DBPORT};
              do echo waiting for Database; sleep 2; done;
          env:
            {{- include "account.container_envs_db" . | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      containers:
        - name: {{ include "module.auth.name" . }}
          securityContext:
            {{- toYaml .Values.global.account.securityContext | nindent 14 }}
          image: {{ include "account.auth.imageUrl" . | quote }}
          imagePullPolicy: {{ .Values.global.account.pullPolicy | default "IfNotPresent" }}
          env:
            - name: SS_CONFIG
              value: "{{ .Values.configPath }}/{{ .Values.configName }}"
            {{- if $auth_data.auth_providers_keys }}
            {{- if $auth_data.auth_providers_keys.apple }}
            - name: AUTH_APPLE_SECRET_PATH
              value: "{{ .Values.configPath }}/apple"
            {{- end }}
            {{- end }}
          {{- include "account.container_envs_redis" . | nindent 12 }}
          {{- include "account.container_envs_db" . | nindent 12 }}
          ports:
            - name: {{ include "account.auth.portHttpName" . }}
              containerPort: {{ include "account.auth.portNumber" . }}
              protocol: {{ include "account.auth.portProtocol" . }}
          volumeMounts:
            - name: {{ $app_name }}-config-volume
              mountPath: {{ .Values.configPath }}/{{ .Values.configName }}
              subPath: {{ .Values.configName }}
            {{- if $auth_data.auth_providers_keys }}
            {{- if $auth_data.auth_providers_keys.apple }}
            - name: auth-apple-secret
              mountPath: {{ .Values.configPath }}/apple
              subPath: apple
            {{- end }}
            {{- end }}
          {{- include "account.auth.resources" . | indent 10 }}

      volumes:
        - name: {{ $app_name }}-config-volume
          configMap:
            name: {{ include "account.auth.configmap.name" . }}
        {{- if $auth_data.auth_providers_keys }}
        {{- if $auth_data.auth_providers_keys.apple }}
        - name: auth-apple-secret
          secret:
            secretName: {{ include "account.auth_provider_secret_name" . }}
            items:
            - key: apple
              path: apple
        {{- end }}
        {{- end }}
      {{- with .Values.global.account.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.account.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.account.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
