{{- $auth_data := .Values.global.account.auth }}
{{- if $auth_data.autoscaling }}
{{- if $auth_data.autoscaling.enabled }}
{{- $autoscaling := $auth_data.autoscaling }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "account.auth.cpuHpa.name" . }}
  labels:
    {{- include "account.auth.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "account.auth.deployment.name" . }}
  minReplicas: {{ $autoscaling.minReplicas }}
  maxReplicas: {{ $autoscaling.maxReplicas }}
  {{- if $autoscaling.targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage: {{ $autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
{{- end }}
