{{- if ne .Values.global.account.config.one_app true }}
{{- if .Values.global.serviceMonitor -}}
{{- if .Values.global.serviceMonitor.enabled -}}
apiVersion: {{ include "common.ServiceMonitor.apiVersion" . }}
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "account.auth.labels" . | nindent 4 }}
    {{- include "common.ServiceMonitor.metadata.labes" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "account.auth.labels" . | nindent 6 }}
  endpoints:
  - path: {{ .Values.prometheusPath | default "/metrics" }}
    targetPort: {{ include "account.auth.portMetricsNumber" . }}
    interval: {{ .Values.prometheusInterval | default "15s" }}
{{- end -}}
{{- end -}}
{{- end }}
