{
 "title": "Account App Dashboard",
 "tags": [ "account" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(go_info{namespace=~\"sa-prod|account-dev|account-pre\"},namespace)"
    }
   },
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(inbound_request_duration_seconds_count,path)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Errors log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"} !~ `my_corezoid_0|http: named cookie not present|SpecifiedUserIsBlocked|AlreadyExist` | json | l = `E`",
     "legendFormat": "{{err}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(err) (sum_over_time(errors_total{namespace=\"$namespace\", err!~\"my_corezoid_0|http: named cookie not present|SpecifiedUserIsBlocked|AlreadyExist|\"}[$__interval]))",
     "legendFormat": "{{err}}"
    }
   ]
  },
  {
   "title": "Inbound RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (type) (increase(inbound_request_duration_seconds_count{namespace=\"$namespace\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{type}} API"
    }
   ]
  },
  {
   "title": "Inbound Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "avg(rate(inbound_request_duration_seconds_sum{namespace=\"$namespace\",path=~\"$path\"}[1m])) by (type) / avg(rate(inbound_request_duration_seconds_count{namespace=\"$namespace\",path=~\"$path\"}[1m])) by (type)",
     "legendFormat": "{{type}} API"
    }
   ]
  },
  {
   "title": "Inbound Error codes percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (new_code) (\n  label_replace(\n    rate(inbound_request_duration_seconds_count{namespace=\"$namespace\",code=~'4..|5..'}[$__range]),\n    \"new_code\",\n    \"${1}xx\",\n    \"code\",\n    \"(^\\\\d).+\"\n  )\n) / \nscalar(sum(rate(inbound_request_duration_seconds_count{namespace=\"$namespace\"}[$__range]))) * 100",
     "legendFormat": "{{new_code}}"
    }
   ]
  },
  {
   "title": "Outbound RPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (type,url) (increase(outbound_request_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{type}}: {{url}}"
    }
   ]
  },
  {
   "title": "Outbound Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "avg(rate(outbound_request_duration_seconds_sum{namespace=\"$namespace\"}[1m])) by (type,url) / avg(rate(outbound_request_duration_seconds_count{namespace=\"$namespace\"}[1m])) by (type,url)",
     "legendFormat": "{{type}}: {{url}}"
    }
   ]
  },
  {
   "title": "Outbound Error codes percentage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (new_code) (\n  label_replace(\n    rate(outbound_request_duration_seconds_count{namespace=\"$namespace\",type=~\"event|notification\",code=~'3..|4..|5..'}[$__range]),\n    \"new_code\",\n    \"${1}xx\",\n    \"code\",\n    \"(^\\\\d).+\"\n  )\n) / \nscalar(sum(rate(outbound_request_duration_seconds_count{namespace=\"$namespace\",type=~\"event|notification\"}[$__range]))) * 100",
     "legendFormat": "{{new_code}}"
    }
   ]
  },
  {
   "title": "Inbound RPM per API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (path) (increase(inbound_request_duration_seconds_count{namespace=\"$namespace\",path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Inbound Latency per API (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg(rate(inbound_request_duration_seconds_sum{namespace=\"$namespace\",path=~\"$path\"}[1m])) by (path) / avg(rate(inbound_request_duration_seconds_count{namespace=\"$namespace\",path=~\"$path\"}[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}