{{- define "account.workspace.resources" }}
{{- if .Values.global.account.workspace.resources }}
{{- $resources := .Values.global.account.workspace.resources }}
resources:
{{ $resources | toYaml | trim | indent 4 }}
{{- else }}
resources:
  limits:
    memory: 400Mi
  requests:
    cpu: 50m
    memory: 200Mi
{{- end }}
{{- end }}
