{{- if eq .Values.global.efs.enabled true}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: singlespace-efs-shared-pv-{{ .Release.Name }}
  labels:
    {{- include "account.pvc.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.global.efs.storageSize | default "5Gi" }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.global.storageClassName }}
  claimRef:
    name: singlespace-efs-shared-pvc
    namespace: {{ .Release.Namespace }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.efs.efsFileSystemId }}
{{- end }}
