{{- $sa_secret_mq := "" }}
{{- $mq_type := "" }}

{{- if .Values.global.account.mq }}
{{- $sa_secret_mq = .Values.global.account.mq.secret }}
{{- $mq_type = .Values.global.account.mq.internal }}
{{- else if .Values.global.mq }}
{{- $sa_secret_mq = .Values.global.mq.secret }}
{{- $mq_type = .Values.global.mq.internal }}
{{- else }}
{{- $sa_secret_mq = nil }}
{{- end }}

{{- if eq .Values.global.account.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workspace.mqSecretName" . }}
  labels:
    app: {{ .Values.global.product }}
    backend: "mq"
type: Opaque
data:
  {{- range $key, $value := $sa_secret_mq.data }}
  {{- if eq $key "host" }}
  {{- if eq $mq_type true }}
  {{ $value := "internal" }}
  {{- end }}
  {{- end }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
