apiVersion: v1
kind: Secret
metadata:
  name: {{ include "account.auth_provider_secret_name" . }}
  labels:
    app: {{ .Values.global.product }}
    backend: "auth"
type: Opaque
data:
  {{- range $key, $value := .Values.global.account.auth.auth_providers_keys }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
