appName: workspace

image:
  repository: account-workspace

configPath: "/opt/conf"
configName: "config.yml"
appAuthLivenessPath: "/liveness"
appAuthReadinessPath: "/readiness"

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
